// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTag: typeof import('element-plus/es')['ElTag']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    MdiArrowRight: typeof import('~icons/mdi/arrow-right')['default']
    MdiCartArrowDown: typeof import('~icons/mdi/cart-arrow-down')['default']
    MdiGithub: typeof import('~icons/mdi/github')['default']
    MdiHeart: typeof import('~icons/mdi/heart')['default']
    MdiHeartOutline: typeof import('~icons/mdi/heart-outline')['default']
    MdiTrash: typeof import('~icons/mdi/trash')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
